---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jussquad

resources:
  - ../../base
  # - deployment.yaml

patches:
  - path: deployment-patch.yaml

# Image transformation (update this with actual registry)
images:
  - name: 783876277037.dkr.ecr.eu-west-3.amazonaws.com/fastapi-sample
    # newName: registry.gitlab.com/proof-of-concept/fastapi-sample
    newTag: latest
