---
stages:
  - static
  - test
  - build
  - train
  - deploy
  - notify

include:
  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/default.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/docker-build.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/deploy-nomad.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/test-python.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/_apk.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/data.gitlab-ci.yml"

  - project: jusmundi-group/infrastructure/ci-templates
    ref: feature-trivyignore
    file: "/templates/mega-linter.gitlab-ci.yml"

  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

  # - project: 'renovate-bot/renovate-runner'
  #   file: '/templates/renovate.gitlab-ci.yml'

  # - remote: https://gitlab.com/renovate-bot/renovate-runner/-/raw/v17.69.3/templates/renovate.gitlab-ci.yml

variables:
  CI_IMAGE_PYTHON: python:3.10
  CI_REGISTRY: registry.gitlab.com
  OCI_REGISTRY: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}
  DOCKER_BUILD_OPT: "--build-arg CI_PIP_GITLABJUSMUNDI_TOKEN=${CI_PIP_GITLABJUSMUNDI_TOKEN} " # --squash
  NOMAD_SERVICE_DEPLOY_URL_SUFFIX: docs
  MOUNT_POINT: "/builds/$CI_PROJECT_PATH/mnt"
  CONTAINER_IMAGE: "$CI_REGISTRY_IMAGE/main-image:latest"
  DEFAULT_POETRY_OPT_GROUPS: "test,open_telemetry,api,test"
  # REGISTRY: 783876277037.dkr.ecr.eu-west-3.amazonaws.com
  DAST_WEBSITE: https://fastapi-sample.service.gra.dev.consul
  CI_IMAGE_NAME: ${CI_REGISTRY}/jusmundi-group/web/templates/jm-oci/jm-ubuntu
  CI_IMAGE_TAG: latest # 0.0.11
  FLAVOR: "-python"
  TRIVY_SCANNERS: "vuln,misconfig,secret"
  # GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'

gemnasium-dependency_scanning:
  variables:
    DS_REMEDIATE: "false"
  # dependencies: ["build"]

# renovate:
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "schedule"'
#     - if: '$CI_PIPELINE_SOURCE == "push"'

.code_navigation:
  image: sourcegraph/lsif-go:latest
  allow_failure: true # recommended
  script:
    - lsif-go
  artifacts:
    reports:
      lsif: dump.lsif

# ======
# Python Code Checks
# ======

.python-check: &python-check
  stage: test
  image: registry.gitlab.com/gitlab-data/data-image/ci-python-image:v1.0.0
  only:
    changes:
      - "**/*.ipynb"
    refs:
      - merge_requests
  allow_failure: true

.python-black:
  <<: *python-check
  script:
    - black --check .

lint-flake8:
  extends: .lint-flake8
  tags:
    - jusmundi-nomad-runner
  variables:
    DEFAULT_FLAKE8_TARGET: "nabla"
    DEFAULT_FLAKE8_ARGS: "--max-line-length=88 --max-complexity=30"
  # BELOW is needed as we do not use jm-ubuntu but python:3.10
  before_script:
    - !reference [.install-pip3, script]
    - !reference [.install-pipenv, script]
    - !reference [.pipenv-install, script]
    - !reference [.install-flake8, script]

lint-ruff:
  extends: .lint-ruff
  needs: ["lint-flake8"]
#  before_script:
#    - !reference [.install-pip3, script]
#    - !reference [.install-pipenv, script]
#    - !reference [.pipenv-install, script]
  interruptible: true
  allow_failure: true

type-checker-pyright:
  extends: .type-checker-pyright
  interruptible: true
  allow_failure: true

test-pytest-poetry:
  extends: .test-pytest-poetry
  needs: ["lint-ruff", "type-checker-pyright"]
  variables:
    DEFAULT_COV_ARGS: "--cov-fail-under=70"
  allow_failure: true

test-pytest:
  extends: .test-pytest
  tags:
    - jusmundi-nomad-runner
  interruptible: true
  allow_failure: true
  needs: ["lint-flake8"]
  variables:
    DEFAULT_COV_ARGS: "--cov-fail-under=70"
    DEFAULT_PIPENV_ARGS: "--system --dev --ignore-pipfile" # --dev  --verbose --index=https://package_read:${CI_PIP_GITLABJUSMUNDI_TOKEN}@gitlab.com/api/v4/groups/7364654/-/packages/pypi/simple
  # BELOW is needed as we do not use jm-ubuntu but python:3.10
  before_script:
    # - export PIPENV_INSTALL_TIMEOUT=1800 # 900 is 15 minutes
    # - !reference [.install-pip3, script]
    - !reference [.install-pipenv, script]
    - !reference [.pipenv-install, script]

mega_linter:
  extends: .mega_linter_common
  needs: ["test-pytest"]
  allow_failure: true

docker-build:
  extends: .docker-build
  tags:
    - jusmundi-nomad-runner
    # - docker # no space left on device
  timeout: 2 hours 10 minutes
  variables:
    CS_SEVERITY_THRESHOLD: "CRITICAL"
    CS_SEVERITY_FILESYTEM_THRESHOLD: "CRITICAL"
    # CUSTOM_CONTAINER_SCANNING_DISABLED: "true"
    # CONTAINER_SCANNING_GITLAB_CODEQUALITY_TEMPLATE_DISABLE: "true"
    TRIVY_TIMEOUT: "20m0s"
    TRIVY_SCANNERS: "vuln"
    TRIVY_ARGS: "--debug --skip-dirs .direnv --skip-dirs .venv --skip-dirs code/.venv --skip-dirs code/.venv/lib/python3.10/site-packages/ --skip-files /code/fastapi-sample/pyproject.toml --skip-files /code/fastapi-sample/Pipfile --skip-files /code/fastapi-sample/pip.conf --skip-files code/fastapi-sample/Dockerfile.train_neuralcoref"
    # TRIVY_EXIT_ON_FAILURE: 0
    # TRIVY_FILESYTEM_EXIT_ON_FAILURE: 0
  after_script:
    - !reference [.combine-reports, script]
    - echo -e "\e[35mImage generated\e[0m."
    - !reference [.oci-image, script]
    - !reference [.login-gitlab-docker, script]
    # - !reference [.login-ecr, script]
    - !reference [.common-docker-release, script]

code_quality:
  extends: .code_quality
  stage: build
  needs: ["docker-build", "lint-ruff", "type-checker-pyright"]
  dependencies:
    - docker-build
    - lint-ruff
    - type-checker-pyright
  script:
    - |-
      if [[ $CONTAINER_SCANNING_GITLAB_CODEQUALITY_TEMPLATE_DISABLE != "true" ]]; then
        jq -s 'add' report_ruff.json report_pyright.json > gl-codeclimate.json || true;
      else
        echo "Disable report_ruff.json report_pyright.json report combine";
      fi

train-commit-activated:
  stage: train
  image: $CONTAINER_IMAGE
  tags:
    - saas-linux-medium-amd64-gpu-standard
  script:
    - echo "GPU training activated by commit message"
    - echo "message passed is $CI_COMMIT_MESSAGE"
    - notebookName=$(echo ${CI_COMMIT_MESSAGE/train})
    - echo "Notebook name $notebookName"
    - papermill -p is_local_development False -p tree_method 'gpu_hist' $notebookName -
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /\w+\.ipynb/
      when: always
      allow_failure: true
  artifacts:
    paths:
      - ./model_metrics.md

cml:
  stage: notify
  image: dvcorg/cml-py3:latest
  script:
    - cml-send-comment model_metrics.md
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\w+\.ipynb/
      when: always
      allow_failure: true

deploy:dev:
  extends: .deploy:dev
  needs: ["docker-build"]
  tags:
    - jusmundi-nomad-runner

deploy:uat:
  extends: .deploy:uat
  needs: ["docker-build"]
  tags:
    - jusmundi-nomad-runner

deploy:prod:
  extends: .deploy:prod
  #needs: ["docker-build"]
  tags:
    - jusmundi-nomad-runner
