# This is the default gitleaks configuration file.
# Rules and allowlists are defined within this file.
title = "gitleaks config"
minVersion = "v8.25.0"

[extend]
useDefault = true

[allowlist]
description = "global allow lists"
regexes = [
    '''219-09-9999''',
    '''078-05-1120''',
    '''(9[0-9]{2}|666)-\d{2}-\d{4}''',
    '''#nosec''',
    '''allow:gitleaks''',
    '''password-reset-XXX''',
    '''sk-1234567890''',
    '''tg3zLMS/bebJFl0LxctiCw''',
]
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|docx|zip|xls|pdf|bin|svg|socket|vsidx|v2|suo|wsuo|.dll|pdb|exe)$''',
    '''(go.mod|go.sum|go.work|go.work.sum)$''',
    '''gradle.lockfile''',
    '''megalinter-reports''',
    '''node_modules''',
    '''open-webui/''',
    '''.mypy_cache''',
    '''(.*?)gitleaks\.toml$''',
    '''vue-client/node_modules''',
    '''package-lock.json''',
    '''yarn.lock''',
    '''pnpm-lock.yaml''',
    '''(^|/)uv\.lock$''',
    '''(^|/)Pipfile\.lock$''',
    '''(^|/)trivy-sbom\.json$''',
    '''Database.refactorlog''',
    '''vendor/''',
    '''.venv/''',
    '''.direnv/''',
    '''.tox/''',
    '''environment.yml''',
    '''.terraform''',
]
