# pytest.ini
[pytest]
python_files = tests.py test_*.py *_test.py
minversion = 5.4
junit_family=xunit1
testpaths =
    tests
# Do not run below test on github or CI as package is not yet installed
#    test
# asyncio_mode to handle async test functions in pytest
asyncio_mode = auto
addopts = -v
filterwarnings =
    ignore:Your application has authenticated using end user credentials:UserWarning
    ignore:PipelineMaxLoops is deprecated:DeprecationWarning
    ignore:`clean_up_tokenization_spaces` was not set:FutureWarning
    ignore:The sentencepiece tokenizer:UserWarning
    ignore:PipelineMaxLoops is deprecated:DeprecationWarning

env =
    AZURE_OCR_ENDPOINT=mocked-azure-ocr-endpoint
    AZURE_OCR_KEY=mocked-azure-ocr-endpoint
    UPTRACE_CREDENTIALS=mocked-uptrace-credentials
    INFERENCE_ENDPOINT_URL_GPU=mocked-inference-url-gpu
    INFERENCE_ENDPOINT_URL_CPU=mocked-inference-url-cpu
    INFERENCE_API_KEY=mocked-inference-api-key
    OPENAI_API_KEY=mocked-openai-api-key
    DB_URL="postgresql://back:backpass@127.0.0.1:5432/back?serverVersion=11.7&charset=utf8"
    DB_PASS="mocked-password-reset-on-XXX"
    MAIL_PASSWORD=mocked-mail-pass
    OVH_APPLICATION_KEY="mocked-ovh-application-key"
    OVH_APPLICATION_SECRET="mocked-ovh-application-secret"
    OVH_CONSUMER_KEY="mocked-ovh-consumer-key"
    OAUTH_TOKEN_SECRET="mocked-oauth-token-secret"
    UNLEASH_API_TOKEN="mocked-unleqsh-api-token"

timeout = 300
