# content of pytest.toml
[pytest]
addopts = ["-p", "no:ddtrace"]
markers = [
    "webtest: mark a test as a webtest.",
    "slow: mark test as slow.",
    "integration: requires explicitly provisioned external services.",
]
