# pytest.ini
[pytest]
python_files = tests.py test_*.py *_test.py
minversion = 5.4
junit_family=xunit1
testpaths =
    tests
# Do not run below test on github or CI as package is not yet installed
#    test
# asyncio_mode to handle async test functions in pytest
asyncio_mode = auto
addopts = -v
filterwarnings =
    ignore:Your application has authenticated using end user credentials:UserWarning
    ignore:PipelineMaxLoops is deprecated:DeprecationWarning
    ignore:`clean_up_tokenization_spaces` was not set:FutureWarning
    ignore:The sentencepiece tokenizer:UserWarning
    ignore:PipelineMaxLoops is deprecated:DeprecationWarning

env =
    AZURE_OCR_ENDPOINT=mocked-azure-ocr-endpoint
    AZURE_OCR_KEY=mocked-azure-ocr-endpoint
    UPTRACE_CREDENTIALS=mocked-uptrace-credentials
    INFERENCE_ENDPOINT_URL_GPU=mocked-inference-url-gpu
    INFERENCE_ENDPOINT_URL_CPU=mocked-inference-url-cpu
    INFERENCE_API_KEY=mocked-inference-api-key
    OPENAI_API_KEY=mocked-openai-api-key

timeout = 300
