[tox]
minversion = 4.16.0
envlist = clean, ruff, py313, package_description, docs
skip_missing_interpreters = True

[testenv]
install_command = uv pip install {opts} {packages}
deps =
    pytest
allowlist_externals = uv
# permet à tox d'utiliser uv pour installer

[testenv:clean]
commands = rm -Rf _build/ build/ .eggs/ dist/ output/pytest-report.xml .coverage output/coverage.xml docs/_build/ .scannerwork/ .pytest_cache/ output/htmlcov/ cprofile pytest-report.xml coverage.xml
allowlist_externals=rm

[testenv:py313]
description = run the tests with pytest under {basepython}
basepython = python3.13
setenv = PIP_DISABLE_VERSION_CHECK = 1
         COVERAGE_FILE = {env:COVERAGE_FILE:{toxworkdir}/.coverage.{envname}}
deps =
    {[testenv]deps}
allowlist_externals = uv

[testenv:ruff]
description = Run code checks and formatting with ruff
deps =
    ruff
commands =
    ruff format .
    ruff check .
allowlist_externals = uv

[testenv:linters]
deps =
    ruff
commands =
    ruff check . {posargs}
    bandit-baseline -r bandit -ll -ii
allowlist_externals = uv

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
basepython = python3.13
extras = docs
deps =
    {[testenv]deps}
commands = sphinx-build ./docs/source/ _build --color -W -bhtml
           python -c 'import pathlib; print("documentation available under file://{0}".format(pathlib.Path(r"{toxworkdir}") / "_build" / "index.html"))'
usedevelop = True
allowlist_externals = uv

[testenv:package_description]
description = check that the long description is valid
basepython = python3.13
deps = twine >= 1.12.1
       readme-renderer[md] >= 30.0
       pip >= 24.1.2
skip_install = true
extras =
commands = pip wheel -w {envtmpdir}/build --no-deps .
           twine check {envtmpdir}/build/*
allowlist_externals = uv

[testenv:fix_lint]
description = format the code base to adhere to our styles, and complain about what we cannot do automatiquement
basepython = python3.13
passenv = {[testenv]passenv}
          HOMEPATH
          PROGRAMDATA
extras = lint
deps =
    {[testenv]deps}
skip_install = True
commands = pre-commit run --all-files --show-diff-on-failure
           python -c 'import pathlib; print("hint: run {} install to add checks as pre-commit hook".format(pathlib.Path(r"{envdir}") / "bin" / "pre-commit"))'
allowlist_externals = uv

[testenv:report]
deps = coverage
depends =
    py313: testenv
skip_install = true
setenv = COVERAGE_FILE={toxworkdir}/.coverage
commands = coverage combine
           coverage report -m
           coverage xml -o output/coverage.xml
           coverage html -d output/htmlcov
allowlist_externals = uv

[testenv:coverage]
description = [run locally after tests]: combine coverage data and create report;
              generates a diff coverage against origin/master (can be changed by setting DIFF_AGAINST env var)
deps = {[testenv]deps}
       {py313}: testenv
       diff_cover
skip_install = true
passenv = {[testenv]passenv}
          DIFF_AGAINST
setenv = COVERAGE_FILE={toxworkdir}/.coverage
commands = coverage combine
           coverage report -m
           coverage xml -o output/coverage.xml
           coverage html -d output/htmlcov
           diff-cover --compare-branch {env:DIFF_AGAINST:origin/master} output/coverage.xml
allowlist_externals = uv

[testenv:dev]
description = dev environment with all deps at {envdir}
extras = docs
deps = {[testenv]deps}
usedevelop = True
commands = python -m pip list --format=columns
           python -c "print(r'{envpython}')"
allowlist_externals = uv

[pep8]
max-line-length = 99

[gh-actions]
python = 3.13: py313
