apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample
spec:
  replicas: 2
  template:
    metadata:
      labels:
        env: prod
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
