apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-sample
  template:
    metadata:
      labels:
        app: fastapi-sample
    spec:
      containers:
        - name: fastapi-sample
          # image: nginx:latest
          image: 783876277037.dkr.ecr.eu-west-3.amazonaws.com/fastapi-sample:latest
          ports:
            - containerPort: 80
