"""Regression tests for bounded per-service DNS evidence."""

from __future__ import annotations

import socket
from unittest.mock import AsyncMock

import pytest

from nabla.api import dns_probe


def test_parse_resolv_conf_keeps_unique_nameservers() -> None:
    assert dns_probe._parse_resolv_conf(
        """
        # generated by runtime
        nameserver 127.0.0.11
        nameserver 1.1.1.1 # fallback
        nameserver 127.0.0.11
        search example.test
        """,
    ) == ("127.0.0.11", "1.1.1.1")


def test_resolver_display_identifies_known_public_and_docker_dns() -> None:
    assert dns_probe._resolver_display("127.0.0.11") == "127.0.0.11 (Docker embedded DNS)"
    assert dns_probe._resolver_display("1.1.1.1") == "1.1.1.1 (Cloudflare DNS)"
    assert dns_probe._resolver_display("9.9.9.9") == "9.9.9.9 (Quad9)"
    assert dns_probe._resolver_display("172.17.0.1") == "172.17.0.1"


@pytest.mark.asyncio
async def test_probe_dns_hostname_reports_resolver_latency_and_answers(monkeypatch) -> None:
    monkeypatch.setattr(dns_probe, "system_dns_resolvers", lambda: ("172.17.0.1",))
    monkeypatch.setattr(
        dns_probe.asyncio,
        "to_thread",
        AsyncMock(
            return_value=[
                (socket.AF_INET, socket.SOCK_STREAM, 6, "", ("192.0.2.10", 0)),
                (socket.AF_INET6, socket.SOCK_STREAM, 6, "", ("2001:db8::10", 0, 0, 0)),
            ],
        ),
    )

    result = await dns_probe.probe_dns_hostname("sample.example")

    assert result["dns_state"] == "ok"
    assert result["dns_hostname"] == "sample.example"
    assert result["dns_probe"] == "getaddrinfo"
    assert result["dns_resolvers"] == ["172.17.0.1"]
    assert result["dns_resolver_source"] == "/etc/resolv.conf"
    assert result["dns_resolved"] == ["192.0.2.10", "2001:db8::10"]
    assert isinstance(result["dns_latency_ms"], int)


@pytest.mark.asyncio
async def test_probe_dns_hostname_preserves_failure_evidence(monkeypatch) -> None:
    monkeypatch.setattr(dns_probe, "system_dns_resolvers", lambda: ("1.1.1.1 (Cloudflare DNS)",))
    monkeypatch.setattr(
        dns_probe.asyncio,
        "to_thread",
        AsyncMock(side_effect=socket.gaierror("name not known")),
    )

    result = await dns_probe.probe_dns_hostname("missing.example")

    assert result["dns_state"] == "fail"
    assert result["dns_resolved"] == []
    assert result["dns_error"] == "name not known"
    assert result["dns_resolvers"] == ["1.1.1.1 (Cloudflare DNS)"]
