apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  # See https://helm.sh/docs/chart_best_practices/labels/
  labels:
    environment: dev
    app.kubernetes.io/name: "{{ template "service.name" . }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service  }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/component: sample
    app.kubernetes.io/part-of: test
    app.kubernetes.io/managed-by: helm
    app: "{{ template "service.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: "{{ .Release.Service  }}"
    release: "{{ .Release.Name }}"
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "service.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "service.selectorLabels" . | nindent 8 }}
        app: {{ template "service.name" . }}
        chart: {{ template "service.chart" . }}
        tier: frontend
        track: canary
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # shareProcessNamespace: true
      # initContainers:
      #   - name: sleep
      #     image: debian:stretch
      #     imagePullPolicy: Always
      #     command:
      #       - sh
      #       - -c
      #       - 'echo "create by init-container" > /secrets/file'
      #     volumeMounts:
      #       - mountPath: /secrets
      #         name: shared
      containers:
        - name: {{ .Chart.Name }}
          # command: ["java", "-Djava.io.tmpdir=/home/jenkins/", "-jar", "/opt/jetty-runner.jar", "/opt/test.war"]
          {{- if hasKey .Values "command" }}
          command: {{ .Values.command }}
          {{- end}}
          # args: ["--version"]
          {{- if and (hasKey .Values "command") (hasKey .Values "args") }}
          args:
          {{- range .Values.args }}
          - "{{ . }}"
          {{- end}}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: TITLE
              value: "Welcome to (EKS)"
          image: "{{ .Values.global.registry }}{{ .Values.image.repository }}:{{ default .Values.image.tag .Chart.AppVersion  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          terminationMessagePath: "/tmp/my-log"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              hostPort: 8091
              protocol: TCP
          # See https://kubernetes.io/fr/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 12 # ~2 minutes
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-cm
            {{- if .Values.secret_from_vault.enabled }}
            - secretRef:
                name: {{ .Release.Name }}-secret
            {{- end }}
            {{- if .Values.sopsSecrets.enabled }}
            - secretRef:
                name: {{ .Release.Name }}-sops-secret
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            # - mountPath: /secrets
            #   name: shared
        - name: shell
          image: busybox
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
              drop:
              - ALL
          stdin: true
          tty: true
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        # - name: shared
        #   # emptyDir: {}
        #   emptyDir:
        #     medium: Memory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
