{{- if .Values.sopsSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sops-secret
  labels:
    {{- include "service.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sopsSecrets.data }}
  {{- range $k, $v := .Values.sopsSecrets.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- else }}
  {{- range .Values.sopsSecrets.keys }}
  {{- $v := index $.Values . }}
  {{- if $v }}
  {{ . }}: {{ $v | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
